[project]
name = "data-engineer-challenge"
version = "0.1.0"
description = "Globant Data Engineering Coding Challenge"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "uvicorn>=0.34.0",
]
